### ISSUE TITLE
create_trapping_clips: "arial.ttf" not found on Linux

### ISSUE THREAD

**Issue by gabrielmittag** [microsoft/P.910#14]
"arial.ttf" cannot be found on Ubuntu. Could maybe add an optional input argument for the font?

```
Start creating files
Traceback (most recent call last):
  File "create_trapping_clips.py", line 207, in <module>
    n_created_files = create_trap_db(tp_cfg, args.source, args.des)
  File "create_trapping_clips.py", line 129, in create_trap_db
    msg_videos = create_msg_video(cfg, des, s_f)
  File "create_trapping_clips.py", line 44, in create_msg_video
    create_msg_img(cfg, score, des, width, height)
  File "create_trapping_clips.py", line 85, in create_msg_img
    font = ImageFont.truetype("arial.ttf", font_size)
  File "/home/gmittag/miniconda3/lib/python3.8/site-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/home/gmittag/miniconda3/lib/python3.8/site-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/gmittag/miniconda3/lib/python3.8/site-packages/PIL/ImageFont.py", line 247, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by mehulmadaan02** [comment]
Verify that the font file "arial.ttf" is present on your instance. You can use the ls command to check if the file exists in the expected location:
**1. ls /usr/share/fonts/truetype/msttcorefonts/arial.ttf**

If the font file is not present, you can install it by running the following command:
**1. sudo apt-get update
2. sudo apt-get install ttf-mscorefonts-installer**
